import React, { useState } from 'react';
import { Share2, Printer, Copy, Check, FileText } from 'lucide-react';
import { PartyProfile, ShoppingItem, StoreType } from '../types';
import { formatCurrency } from '../utils/calculations';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  party: PartyProfile;
  items: ShoppingItem[];
}

const STORE_NAMES: Record<StoreType, string> = {
  supermarket: 'Grocery / Supermarket',
  wholesale_club: 'Wholesale Club (Costco / Sam\'s)',
  party_discount: 'Party Supply & Dollar Store',
  specialty_bakery: 'Bakery / Specialty Deli',
  liquor_beverage: 'Liquor & Beverage Store',
  online_delivery: 'Online Orders & Ahead Delivery',
};

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  party,
  items,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const totalCost = items.reduce((acc, it) => acc + it.estimatedTotalCost, 0);

  // Group items by store for the physical shopping trips
  const storeGroups: Record<string, ShoppingItem[]> = {};
  items.forEach((item) => {
    const store = item.storeSuggestion || 'supermarket';
    if (!storeGroups[store]) storeGroups[store] = [];
    storeGroups[store].push(item);
  });

  const generateFormattedText = () => {
    let output = `🎉 PARTY SHOPPING CHECKLIST: ${party.title.toUpperCase()}\n`;
    output += `Theme: ${party.theme} | Guests: ${party.guestCount} (${party.adultCount} adults, ${party.kidCount} kids)\n`;
    output += `Budget Target: ${formatCurrency(party.budget)} | Estimated Total: ${formatCurrency(totalCost)}\n`;
    if (party.dietaryRestrictions.length > 0) {
      output += `Dietary Needs: ${party.dietaryRestrictions.join(', ')}\n`;
    }
    output += `\n=========================================\n`;

    Object.entries(storeGroups).forEach(([storeKey, storeItems]) => {
      const storeName = STORE_NAMES[storeKey as StoreType] || storeKey;
      output += `\n🛒 ${storeName.toUpperCase()} (${storeItems.length} items):\n`;
      storeItems.forEach((it) => {
        const check = it.isPurchased ? '[x]' : '[ ]';
        const diet = it.dietaryTag ? ` [${it.dietaryTag}]` : '';
        const desc = it.packageDescription ? ` - ${it.packageDescription}` : '';
        output += `${check} ${it.name} - Qty: ${it.quantity} ${it.unit} (~${formatCurrency(it.estimatedTotalCost)})${diet}${desc}\n`;
      });
    });

    output += `\n=========================================\n`;
    output += `Generated by Party Planner Shopping Agent\n`;
    return output;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateFormattedText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-900/40 backdrop-blur-xs p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-2xl w-full p-6 shadow-2xl border border-stone-200 animate-in fade-in zoom-in-95 duration-150 my-8">
        <div className="flex items-center justify-between pb-4 border-b border-stone-100">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-amber-600 text-white flex items-center justify-center">
              <Share2 className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-stone-900">Export & Print Shopping List</h2>
              <p className="text-xs text-stone-500">Organized by store run for smooth shopping</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="text-stone-400 hover:text-stone-600 text-sm font-semibold p-1"
          >
            ✕
          </button>
        </div>

        {/* Text Preview Box */}
        <div className="mt-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-xs font-semibold text-stone-700">Preview formatted list:</span>
            <div className="flex gap-2">
              <button
                type="button"
                onClick={handleCopy}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-stone-100 hover:bg-stone-200 text-stone-800 text-xs font-semibold rounded-lg transition-colors border border-stone-300"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy to Clipboard'}</span>
              </button>
              <button
                type="button"
                onClick={handlePrint}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-stone-900 hover:bg-stone-800 text-white text-xs font-semibold rounded-lg shadow-xs transition-colors"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print List</span>
              </button>
            </div>
          </div>

          <pre className="p-4 bg-stone-50 border border-stone-200 rounded-xl text-[11px] text-stone-800 font-mono overflow-y-auto max-h-96 whitespace-pre-wrap leading-relaxed select-all">
            {generateFormattedText()}
          </pre>
        </div>

        <div className="flex justify-end pt-4 border-t border-stone-100 mt-4">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 border border-stone-300 text-stone-700 font-semibold rounded-lg hover:bg-stone-50 text-xs"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
